require("plugins")
require("global_settings")
require("editor_settings")
require("mappings")

require("core.nvim-cmp")
require("core.nvim-autopairs")
require("core.treesitter")
require("core.galaxyline")
-- require("core.indent-guides")
require("core.nvim-tree")
require("core.vimtex")

require("lsp")
require('lsp.clangd')
require('lsp.lua-ls')
require('lsp.python-ls')
-- require('lsp.bash-ls')
-- require('lsp.css-ls')
-- require('lsp.docker-ls')
-- require('lsp.efm-general-ls')
-- require('lsp.emmet-ls')
-- require('lsp.html-ls')
-- require('lsp.js-ts-ls')
-- require('lsp.latex-ls')
-- require('lsp.php-ls')
-- require('lsp.rust-ls')
-- require('lsp.vim-ls')
