require('global_settings')
-- vim.cmd('luafile '..CONFIG_PATH..'/lv-settings.lua') -- now redundant user settings
require('editor_settings')
require('lv-gitblame')
require('plugins')
require('lua_utils')
require('autocommands')
require('autopairs')
require('keymappings')
require('lv-nvimtree') -- must be required before colorscheme
require('colorscheme') -- must be required after nvimtree
require('galaxyline_config')
require('lv-comment')
require('lv-gitblame')
require('compe_config')
require('barbar_config')
require('dashboard_config')
require('telescope_config')
require('lv-gitsigns')
require('lv-treesitter')
require('lv-matchup')
require('lv-rnvimr')
require('lv-which-key')
require('lv-lsp-rooter')
require('lv-zen')

-- LSP
require('lsp_config')
require('lsp_config.angular-ls')
require('lsp_config.bash-ls')
require('lsp_config.clangd')
require('lsp_config.cmake-ls')
require('lsp_config.css-ls')
require('lsp_config.dart-ls')
require('lsp_config.docker-ls')
require('lsp_config.efm-general-ls')
require('lsp_config.elm-ls')
require('lsp_config.emmet-ls')
require('lsp_config.graphql-ls')
require('lsp_config.go-ls')
require('lsp_config.html-ls')
require('lsp_config.json-ls')
require('lsp_config.js-ts-ls')
require('lsp_config.kotlin-ls')
require('lsp_config.latex-ls')
require('lsp_config.lua-ls')
require('lsp_config.php-ls')
require('lsp_config.python-ls')
require('lsp_config.ruby-ls')
require('lsp_config.rust-ls')
require('lsp_config.svelte-ls')
require('lsp_config.terraform-ls')
require('lsp_config.vim-ls')
require('lsp_config.vue-ls')
require('lsp_config.yaml-ls')
require('lsp_config.elixir-ls')
-- require('lsp.tailwindcss-ls')

-- extras
if Global.extras then
    require('lv-numb')
    require('lv-dial')
    require('lv-hop')
    require('lv-colorizer')
    require('lv-symbols-outline')
end

vim.cmd('source '..CONFIG_PATH..'/vimscript/functions.vim')
vim.g.nvim_tree_auto_close = 1 -- 0 by default, closes the tree when it's the last window
