require("config.autopairs")
require("config.comment")
require("config.bufferline")
require("config.gitsigns")
require("config.indentblankline")
require("config.lualine")
require("config.treesitter")
require("config.bqf")

require("config.mason")
require("config.lsp")
require("config.completion")
