require("config.autopairs")
require("config.bufferline")
require("config.gitsigns")
require("config.indentblankline")
require("config.lsp")
require("config.lualine")
require("config.luasnip")
require("config.lsp_signature")
-- require("config.nvimtree")
require("config.mason")
require("config.treesitter")
require("config.cmp")
