require("config.autopairs")
require("config.bufferline")
require("config.gitsigns")
require("config.indentblankline")
require("config.lualine")
require("config.treesitter")
require("config.bqf")
require("config.mason")
require("config.lsp")

require("config.completion")
-- completion disabled for now
-- require("config.luasnip_config")
-- require("config.cmp")
-- local lsp = require('lsp-zero')
-- lsp.preset('recommended')
-- lsp.nvim_workspace()
-- lsp.setup()
