require'nvim-treesitter'.install( {
    "asm",
    "bash",
    "cmake",
    "cpp",
    "css",
    "csv",
    "c",
    "diff",
    "dot",
    "dockerfile",
    "gitcommit",
    "gitignore",
    "git_config",
    "git_rebase",
    "gnuplot",
    "go",
    "goctl",
    "gomod",
    "gosum",
    "gpg",
    "graphql",
    "hcl",
    "http",
    "ini",
    "java",
    "javascript",
    "jq",
    "json",
    "json5",
    "kotlin",
    "latex",
    "lua",
    "luadoc",
    "make",
    "markdown",
    "markdown_inline",
    "nasm",
    "nix",
    "php",
    "promql",
    "python",
    "proto",
    "rst",
    "sql",
    "ssh_config",
    "strace",
    "terraform",
    "html",
    "svelte",
    "sway",
    "tmux",
    "toml",
    "tsx",
    "typescript",
    "udev",
    "vim",
    "yaml",
    "xresources",
})

require("nvim-ts-autotag").setup()

-- vim.cmd([[
-- set foldmethod=expr
-- set foldexpr=nvim_treesitter#foldexpr()
-- set nofoldenable
-- ]])

require("treesitter-context").setup({
  enable = true,
  max_lines = 0,
  min_window_height = 0,
  line_numbers = true,
  multiline_threshold = 20,
  trim_scope = "outer",
  mode = "cursor",
  separator = "─",
  zindex = 20,
  on_attach = nil,
})
