local utils = require('utils')


vim.api.nvim_set_keymap('n', '<C-Up>', ':resize -2<CR>', {silent = true})
vim.api.nvim_set_keymap('n', '<C-Down>', ':resize +2<CR>', {silent = true})
vim.api.nvim_set_keymap('n', '<C-Left>', ':vertical resize -2<CR>', {silent = true})
vim.api.nvim_set_keymap('n', '<C-Right>', ':vertical resize +2<CR>', {silent = true})
utils.map('', '<leader>wh', '<C-w>h')
utils.map('', '<leader>wj', '<C-w>j')
utils.map('', '<leader>wk', '<C-w>k')
utils.map('', '<leader>wl', '<C-w>l')
utils.map('', '/', '/\\c')
vim.api.nvim_set_keymap('v', '<', '<gv', {noremap = true, silent = true})
vim.api.nvim_set_keymap('v', '>', '>gv', {noremap = true, silent = true})
vim.api.nvim_set_keymap('i', 'jk', '<ESC>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('i', 'kj', '<ESC>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('i', 'jj', '<ESC>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<TAB>', ':bnext<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<S-TAB>', ':bprevious<CR>', {noremap = true, silent = true})
vim.cmd('inoremap <expr> <c-j> (\"\\<C-n>\")')
vim.cmd('inoremap <expr> <c-k> (\"\\<C-p>\")')
vim.api.nvim_set_keymap('', '<C-q>', ':call QuickFixToggle()<CR>', {noremap = true, silent = true})
utils.map('', '<leader>ij', 'o<esc>0Dk')
utils.map('', '<leader>ik', 'O<esc>0Dj')
utils.map('', '<leader>tcc', ':set cursorcolumn!<CR>')
utils.map('', '<leader>tcl', ':set cursorline!<CR>')
vim.api.nvim_set_keymap("n", "<leader>/", ":CommentToggle<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("v", "<leader>/", ":CommentToggle<CR>", {noremap = true, silent = true})

--lsp

utils.map('', '<leader>la', ':Lspsaga code_action<CR>')
utils.map('', '<leader>ld', ':Lspsaga show_line_diagnostics<CR>')
utils.map('', '<leader>lf', ':LspFormatting<CR>')
utils.map('', '<leader>lp', ':Lspsaga preview_definition<CR>')
utils.map('', '<leader>lr', ':Lspsaga rename<CR>')
utils.map('', '<leader>lt', ':LspTypeDefinition<CR>')
utils.map('', '<leader>lc', ':cclose<CR>')
-- utils.map('', '<leader>',   ":Lspsaga range_code_action<CR>")
-- utils.map('', '<leader>',   ":Telescope lsp_workspace_diagnostics<CR>")
-- utils.map('', '<leader>',   ":LspInfo<CR>")
-- utils.map('', '<leader>',   ":Lspsaga lsp_finder<CR>")
-- utils.map('', '<leader>',   ":Telescope quickfix<CR>")
