fileExtensionPreference:
    .tex: 1
    .sty: 2
    .cls: 3
    .bib: 4

backupExtension: .bak

onlyOneBackUp: 0

maxNumberOfBackUps: 0

cycleThroughBackUps: 0

logFilePreferences:
    showEveryYamlRead: 1
    showAmalgamatedSettings: 0
    showDecorationStartCodeBlockTrace: 0
    showDecorationFinishCodeBlockTrace: 0
    endLogFileWith: '--------------'
    showGitHubInfoFooter: 1
    Dumper:
      Terse: 1
      Indent: 1
      Useqq: 1
      Deparse: 1
      Quotekeys: 0
      Sortkeys: 1
      Pair: " => "

verbatimEnvironments:
    verbatim: 1
    lstlisting: 1
    minted: 1

verbatimCommands:
    verb: 1
    lstinline: 1

noIndentBlock:
    noindent: 1
    cmhtest: 1

fileContentsEnvironments:
    filecontents: 1
    filecontents*: 1

indentPreamble: 0

lookForPreamble:
    .tex: 1
    .sty: 0
    .cls: 0
    .bib: 0

preambleCommandsBeforeEnvironments: 0

defaultIndent: "  "

removeTrailingWhitespace:
    beforeProcessing: 0
    afterProcessing: 1

lookForAlignDelims:
   tabular:
      delims: 1
      alignDoubleBackSlash: 1
      spacesBeforeDoubleBackSlash: 1
      multiColumnGrouping: 0
      alignRowsWithoutMaxDelims: 1
      spacesBeforeAmpersand: 1
      spacesAfterAmpersand: 1
      justification: left
      alignFinalDoubleBackSlash: 0
      dontMeasure: 0
      delimiterRegEx: (?<!\\)(&)
      delimiterJustification: left
      lookForChildCodeBlocks: 1
   tabularx:
      delims: 1
   longtable: 1
   tabu: 1
   array: 1
   matrix: 1
   listabla: 1
   align: 1
   align*: 1
   alignat: 1
   alignat*: 1
   aligned: 1
   bmatrix: 1
   Bmatrix: 1
   cases: 1
   flalign: 1
   flalign*: 1
   pmatrix: 1
   vmatrix: 1
   Vmatrix: 1
   cases*: 1
   dcases: 1
   dcases*: 1
   rcases: 1
   rcases*: 1
   drcases: 1
   drcases*: 1
   NiceTabular: 1
   NiceMatrix: 1
   pNiceMatrix: 1
   bNiceMatrix: 1
   BNiceMatrix: 1
   vNiceMatrix: 1
   VNiceMatrix: 1
   NiceArray: 1
   pNiceArrayC: 1
   bNiceArrayC: 1
   BNiceArrayC: 1
   vNiceArrayC: 1
   VNiceArrayC: 1
   NiceArrayCwithDelims: 1
   pNiceArrayRC: 1
   bNiceArrayRC: 1
   BNiceArrayRC: 1
   vNiceArrayRC: 1
   VNiceArrayRC: 1
   NiceArrayRCwithDelims: 1
   tblr: 1
   longtblr: 1
   talltblr: 1

indentAfterItems:
    itemize: 1
    itemize*: 1
    enumerate: 1
    enumerate*: 1
    description: 1
    description*: 1
    list: 1

itemNames:
    item: 1
    myitem: 1

specialBeginEnd:
    displayMath:
        begin: (?<!\\)\\\[
        end: \\\]
        lookForThis: 1
    inlineMath:
        begin: (?<!\$)(?<!\\)\$(?!\$)
        end: (?<!\\)\$(?!\$)
        lookForThis: 1
    displayMathTeX:
        begin: \$\$
        end: \$\$
        lookForThis: 1
    specialBeforeCommand: 0

indentAfterHeadings:
    part:
       indentAfterThisHeading: 0
       level: 1
    chapter:
       indentAfterThisHeading: 0
       level: 2
    section:
       indentAfterThisHeading: 0
       level: 3
    subsection:
       indentAfterThisHeading: 0
       level: 4
    subsection*:
       indentAfterThisHeading: 0
       level: 4
    subsubsection:
       indentAfterThisHeading: 0
       level: 5
    paragraph:
       indentAfterThisHeading: 0
       level: 6
    subparagraph:
       indentAfterThisHeading: 0
       level: 7

maximumIndentation: -1

noAdditionalIndent:
    myexample: 1
    mydefinition: 1
    problem: 1
    exercises: 1
    mysolution: 1
    foreach: 0
    widepage: 1
    comment: 1
    document: 1
    frame: 0

indentRules:
   myenvironment: "  "
   anotherenvironment: "  "
   chapter: "  "
   section: "  "
   item: "  "
   myitem: "  "

noAdditionalIndentGlobal:
    environments: 0                   # 0/1
    commands: 1                       # 0/1
    optionalArguments: 0              # 0/1
    mandatoryArguments: 0             # 0/1
    ifElseFi: 0                       # 0/1
    items: 0                          # 0/1
    keyEqualsValuesBracesBrackets: 0  # 0/1
    namedGroupingBracesBrackets: 0    # 0/1
    UnNamedGroupingBracesBrackets: 0  # 0/1
    specialBeginEnd: 0                # 0/1
    afterHeading: 0                   # 0/1
    filecontents: 0                   # 0/1

indentRulesGlobal:
    environments: 0                   # 0/h-space
    commands: 0                       # 0/h-space
    optionalArguments: 0              # 0/h-space
    mandatoryArguments: 0             # 0/h-space
    ifElseFi: 0                       # 0/h-space
    items: 0                          # 0/h-space
    keyEqualsValuesBracesBrackets: 0  # 0/h-space
    namedGroupingBracesBrackets: 0    # 0/h-space
    UnNamedGroupingBracesBrackets: 0  # 0/h-space
    specialBeginEnd: 0                # 0/h-space
    afterHeading: 0                   # 0/h-space
    filecontents: 0                   # 0/h-space

commandCodeBlocks:
    roundParenthesesAllowed: 1
    stringsAllowedBetweenArguments:
      -
        amalgamate: 1
      - node
      - at
      - to
      - decoration
      - \+\+
      - \-\-
      - \#\#\d
    commandNameSpecial:
      -
        amalgamate: 1
      - '@ifnextchar\['

dos2unixlinebreaks: 0

modifyLineBreaks:
    preserveBlankLines: 0                   # 0/1
    condenseMultipleBlankLinesInto: 1       # 0/1
    oneSentencePerLine:
        manipulateSentences: 1              # 0/1
        removeSentenceLineBreaks: 1         # 0/1
        multipleSpacesToSingle: 1           # 0/1
        textWrapSentences: 0                # 1 disables main textWrap
        sentenceIndent: ""
        sentencesFollow:
            par: 1                          # 0/1
            blankLine: 1                    # 0/1
            fullStop: 1                     # 0/1
            exclamationMark: 1              # 0/1
            questionMark: 1                 # 0/1
            rightBrace: 1                   # 0/1
            commentOnPreviousLine: 1        # 0/1
            other: 0                        # regex
        sentencesBeginWith:            
            A-Z: 1                          # 0/1
            a-z: 0                          # 0/1
            other: 0                        # regex
        sentencesEndWith:
            basicFullStop: 0                # 0/1
            betterFullStop: 1               # 0/1
            exclamationMark: 1              # 0/1
            questionMark: 1                 # 0/1
            other: "\\n\\s*\\n"                        # regex
    textWrapOptions:
        columns: 0
        multipleSpacesToSingle: 1              
        removeBlockLineBreaks: 1
        when: before                        # before/after
        comments: 
           wrap: 0                          # 0/1
           inheritLeadingSpace: 0           # 0/1
        blocksFollow:
           headings: 1                      # 0/1
           commentOnPreviousLine: 1         # 0/1
           par: 1                           # 0/1
           blankLine: 1                     # 0/1
           verbatim: 1                      # 0/1
           filecontents: 1                  # 0/1
           other: \\\]|\\item(?:\h|\[)      # regex
        blocksBeginWith:
           A-Z: 1                           # 0/1
           a-z: 1                           # 0/1
           0-9: 0                           # 0/1
           other: 0                         # regex
        blocksEndBefore:
           commentOnOwnLine: 1              # 0/1
           verbatim: 1                      # 0/1
           filecontents: 1                  # 0/1
           other: \\begin\{|\\\[|\\end\{    # regex
        huge: overflow                      # forbid mid-word line breaks
        separator: ""
    environments:                           
        BeginStartsOnOwnLine: 0             # -1,0,1,2,3,4
        BodyStartsOnOwnLine: 0              # -1,0,1,2,3,4
        EndStartsOnOwnLine: 0               # -1,0,1,2,3,4
        EndFinishesWithLineBreak: 0         # -1,0,1,2,3,4
        equation*:                          
            BeginStartsOnOwnLine: 0         # -1,0,1,2,3,4
            BodyStartsOnOwnLine: 0          # -1,0,1,2,3,4
            EndStartsOnOwnLine: 0           # -1,0,1,2,3,4
            EndFinishesWithLineBreak: 0     # -1,0,1,2,3,4
    ifElseFi:
        IfStartsOnOwnLine: 0                # -1,0,1,2,3,4
        BodyStartsOnOwnLine: 0              # -1,0,1,2,3,4
        OrStartsOnOwnLine: 0                # -1,0,1,2,3,4
        OrFinishesWithLineBreak: 0          # -1,0,1,2,3,4
        ElseStartsOnOwnLine: 0              # -1,0,1,2,3,4
        ElseFinishesWithLineBreak: 0        # -1,0,1,2,3,4
        FiStartsOnOwnLine: 0                # -1,0,1,2,3,4
        FiFinishesWithLineBreak: 0          # -1,0,1,2,3,4 
        ifnum:
            IfStartsOnOwnLine: 0            # -1,0,1,2,3,4
            BodyStartsOnOwnLine: 0          # -1,0,1,2,3,4
            OrStartsOnOwnLine: 0            # -1,0,1,2,3,4
            OrFinishesWithLineBreak: 0      # -1,0,1,2,3,4
            ElseStartsOnOwnLine: 0          # -1,0,1,2,3,4
            ElseFinishesWithLineBreak: 0    # -1,0,1,2,3,4
            FiStartsOnOwnLine: 0            # -1,0,1,2,3,4
            FiFinishesWithLineBreak: 0      # -1,0,1,2,3,4 
    commands:
        CommandStartsOnOwnLine: 0          
        CommandNameFinishesWithLineBreak: 0
    optionalArguments:
        LSqBStartsOnOwnLine: 0              # -1,0,1,2,3,4
        OptArgBodyStartsOnOwnLine: 0        # -1,0,1,2,3,4
        RSqBStartsOnOwnLine: 0              # -1,0,1,2,3,4
        RSqBFinishesWithLineBreak: 0        # -1,0,1,2,3,4
    mandatoryArguments:                     
        LCuBStartsOnOwnLine: 0              # -1,0,1,2,3,4
        MandArgBodyStartsOnOwnLine: 0       # -1,0,1,2,3,4
        RCuBStartsOnOwnLine: 0              # -1,0,1,2,3,4 
        RCuBFinishesWithLineBreak: 0        # -1,0,1,2,3,4 
    keyEqualsValuesBracesBrackets:
        KeyStartsOnOwnLine: 0               # -1,0,1,2,3,4
        EqualsStartsOnOwnLine: 0            # -1,0,1,2,3,4
        EqualsFinishesWithLineBreak: 0      # -1,0,1,2,3,4 
    items:                                  
        ItemStartsOnOwnLine: 0              # -1,0,1,2,3,4
        ItemFinishesWithLineBreak: 0        # -1,0,1,2,3,4
    namedGroupingBracesBrackets:
        NameStartsOnOwnLine: 0              # -1,0,1,2,3,4
        NameFinishesWithLineBreak: 0        # -1,0,1,2,3,4
    specialBeginEnd:
        SpecialBeginStartsOnOwnLine: 0      # -1,0,1,2,3,4
        SpecialBodyStartsOnOwnLine: 0       # -1,0,1,2,3,4
        SpecialEndStartsOnOwnLine: 0        # -1,0,1,2,3,4
        SpecialEndFinishesWithLineBreak: 0  # -1,0,1,2,3,4
    verbatim:
        VerbatimBeginStartsOnOwnLine: 0     # -1,0,1,2,3,4
        VerbatimEndFinishesWithLineBreak: 0 # -1,0,1,2,3,4

replacements:
  -
    amalgamate: 1
  -
    this: latexindent.pl
    that: pl.latexindent
    lookForThis: 0
    when: before

fineTuning:
    environments:
      name: [a-zA-Z@\*0-9_\\]+
    ifElseFi:
      name: (?!@?if[a-zA-Z@]*?\{)@?if[a-zA-Z@]*?
    commands:
      name: [+a-zA-Z@\*0-9_\:]+?
    items:
      canBeFollowedBy: (?:\[[^]]*?\])|(?:<[^>]*?>)
    keyEqualsValuesBracesBrackets:
      name: [a-zA-Z@\*0-9_\/.:\#-]+[a-zA-Z@\*0-9_\/.\h\{\}:\#-]*?
      follow: (?:(?<!\\)\{)|,|(?:(?<!\\)\[)
    namedGroupingBracesBrackets:
      name: [0-9\.a-zA-Z@\*><]+?
      follow: \h|\R|\{|\[|\$|\)|\(
    UnNamedGroupingBracesBrackets:
      follow: \{|\[|,|&|\)|\(|\$
    arguments:
      before: (?:#\d\h*;?,?\/?)+|\<.*?\>
      between: _|\^|\*
    trailingComments:
      notPreceededBy: (?<!\\)
    modifyLineBreaks:
      doubleBackSlash: \\\\(?:\h*\[\h*\d+\h*[a-zA-Z]+\h*\])?
      comma: ','
      betterFullStop: |-
        (?x)                                # ignore spaces in the below
        (?:                                 #
          \.\)                              # .) 
          (?!\h*[a-z])                      # not *followed by* a-z
        )                                   #
        |                                   # OR
        (?:                                 #
          (?<!                              # not *preceded by*
            (?:                             #
              (?:[eE]\.[gG])                # e.g OR E.g OR e.G OR E.G
              |                             #
              (?:[iI]\.[eE])                # i.e OR I.e OR i.E OR I.E
              |                             #
              (?:etc)                       # etc
            )                               #
          )                                 #
        )                                   # 
        \.                                  # .
        (?!                                 # not *followed by*
          (?:                               #
            [a-zA-Z0-9-~,]                  #
            |                               #
            \),                             # ),
            |                               #
            \)\.                            # ).
          )                                 #
        )                                   #
